name: anime_store
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  visibility_aware_state: ^1.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  mockito: ^5.4.0
  bloc_test: ^9.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/


